//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtIniSeq {
            get {
                return ((string)(this["userInputtxtIniSeq"]));
            }
            set {
                this["userInputtxtIniSeq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string userInputtxtLongSeq {
            get {
                return ((string)(this["userInputtxtLongSeq"]));
            }
            set {
                this["userInputtxtLongSeq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string userInputtxtIniFieldFileNumber {
            get {
                return ((string)(this["userInputtxtIniFieldFileNumber"]));
            }
            set {
                this["userInputtxtIniFieldFileNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string userInputtxtLongFieldFileNumber {
            get {
                return ((string)(this["userInputtxtLongFieldFileNumber"]));
            }
            set {
                this["userInputtxtLongFieldFileNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public string userInputtxtInicmp {
            get {
                return ((string)(this["userInputtxtInicmp"]));
            }
            set {
                this["userInputtxtInicmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string userInputtxtlongcmp {
            get {
                return ((string)(this["userInputtxtlongcmp"]));
            }
            set {
                this["userInputtxtlongcmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public string userInputtxtIniTraceType {
            get {
                return ((string)(this["userInputtxtIniTraceType"]));
            }
            set {
                this["userInputtxtIniTraceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtLongTraceType {
            get {
                return ((string)(this["userInputtxtLongTraceType"]));
            }
            set {
                this["userInputtxtLongTraceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string userInputtxtIniSourcePoint {
            get {
                return ((string)(this["userInputtxtIniSourcePoint"]));
            }
            set {
                this["userInputtxtIniSourcePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string userInputtxtlongSourcePoint {
            get {
                return ((string)(this["userInputtxtlongSourcePoint"]));
            }
            set {
                this["userInputtxtlongSourcePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public string userInputtxtIniCmp1 {
            get {
                return ((string)(this["userInputtxtIniCmp1"]));
            }
            set {
                this["userInputtxtIniCmp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string userInputtxtLongCmp1 {
            get {
                return ((string)(this["userInputtxtLongCmp1"]));
            }
            set {
                this["userInputtxtLongCmp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81")]
        public string userInputtxtIniOffset {
            get {
                return ((string)(this["userInputtxtIniOffset"]));
            }
            set {
                this["userInputtxtIniOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string userInputtxtLongOffset {
            get {
                return ((string)(this["userInputtxtLongOffset"]));
            }
            set {
                this["userInputtxtLongOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public string userInputtxtIniSourceX {
            get {
                return ((string)(this["userInputtxtIniSourceX"]));
            }
            set {
                this["userInputtxtIniSourceX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string userInputtxtLongSourceX {
            get {
                return ((string)(this["userInputtxtLongSourceX"]));
            }
            set {
                this["userInputtxtLongSourceX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public string userInputtxtIniSourceY {
            get {
                return ((string)(this["userInputtxtIniSourceY"]));
            }
            set {
                this["userInputtxtIniSourceY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string userInputtxtLongSourceY {
            get {
                return ((string)(this["userInputtxtLongSourceY"]));
            }
            set {
                this["userInputtxtLongSourceY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string userInputtxtIniReceiverX {
            get {
                return ((string)(this["userInputtxtIniReceiverX"]));
            }
            set {
                this["userInputtxtIniReceiverX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string userInputtxtLongReceiverX {
            get {
                return ((string)(this["userInputtxtLongReceiverX"]));
            }
            set {
                this["userInputtxtLongReceiverX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("145")]
        public string userInputtxtIniReceiverY {
            get {
                return ((string)(this["userInputtxtIniReceiverY"]));
            }
            set {
                this["userInputtxtIniReceiverY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string userInputtxtLongReceiverY {
            get {
                return ((string)(this["userInputtxtLongReceiverY"]));
            }
            set {
                this["userInputtxtLongReceiverY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public string userInputtxtIniSourceStation {
            get {
                return ((string)(this["userInputtxtIniSourceStation"]));
            }
            set {
                this["userInputtxtIniSourceStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string userInputtxtLongSourceStation {
            get {
                return ((string)(this["userInputtxtLongSourceStation"]));
            }
            set {
                this["userInputtxtLongSourceStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public string userInputtxtIniComponetType {
            get {
                return ((string)(this["userInputtxtIniComponetType"]));
            }
            set {
                this["userInputtxtIniComponetType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtLongComponetType {
            get {
                return ((string)(this["userInputtxtLongComponetType"]));
            }
            set {
                this["userInputtxtLongComponetType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("187")]
        public string userInputtxtIniMainSourceType {
            get {
                return ((string)(this["userInputtxtIniMainSourceType"]));
            }
            set {
                this["userInputtxtIniMainSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtLongMainSourceType {
            get {
                return ((string)(this["userInputtxtLongMainSourceType"]));
            }
            set {
                this["userInputtxtLongMainSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199")]
        public string userInputtxtiniMainInstrumentType {
            get {
                return ((string)(this["userInputtxtiniMainInstrumentType"]));
            }
            set {
                this["userInputtxtiniMainInstrumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtlongMainInstrumentType {
            get {
                return ((string)(this["userInputtxtlongMainInstrumentType"]));
            }
            set {
                this["userInputtxtlongMainInstrumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207")]
        public string userInputtxtIniCmpX {
            get {
                return ((string)(this["userInputtxtIniCmpX"]));
            }
            set {
                this["userInputtxtIniCmpX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string userInputtxtLongCmpX {
            get {
                return ((string)(this["userInputtxtLongCmpX"]));
            }
            set {
                this["userInputtxtLongCmpX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225")]
        public string userInputtxtIniCmpY {
            get {
                return ((string)(this["userInputtxtIniCmpY"]));
            }
            set {
                this["userInputtxtIniCmpY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string userInputtxtLongCmpY {
            get {
                return ((string)(this["userInputtxtLongCmpY"]));
            }
            set {
                this["userInputtxtLongCmpY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("243")]
        public string userInputtxtIniFold {
            get {
                return ((string)(this["userInputtxtIniFold"]));
            }
            set {
                this["userInputtxtIniFold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userInputtxtLongFold {
            get {
                return ((string)(this["userInputtxtLongFold"]));
            }
            set {
                this["userInputtxtLongFold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public string userInputtxtIniCCPNorthing {
            get {
                return ((string)(this["userInputtxtIniCCPNorthing"]));
            }
            set {
                this["userInputtxtIniCCPNorthing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string userInputtxtLongCCPNorthing {
            get {
                return ((string)(this["userInputtxtLongCCPNorthing"]));
            }
            set {
                this["userInputtxtLongCCPNorthing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("271")]
        public string userInputtxtIniCCPElevation {
            get {
                return ((string)(this["userInputtxtIniCCPElevation"]));
            }
            set {
                this["userInputtxtIniCCPElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string userInputtxtLongCCPElevation {
            get {
                return ((string)(this["userInputtxtLongCCPElevation"]));
            }
            set {
                this["userInputtxtLongCCPElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("287")]
        public string userInputtxtIniCCPEasting {
            get {
                return ((string)(this["userInputtxtIniCCPEasting"]));
            }
            set {
                this["userInputtxtIniCCPEasting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string userInputtxtLongCCPEasting {
            get {
                return ((string)(this["userInputtxtLongCCPEasting"]));
            }
            set {
                this["userInputtxtLongCCPEasting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public string userInputtxtstart {
            get {
                return ((string)(this["userInputtxtstart"]));
            }
            set {
                this["userInputtxtstart"] = value;
            }
        }
    }
}
